### ISSUE TITLE
blargbot won't function, even when I do the b!help

### ISSUE THREAD

**Issue by PacMug** [Ratismal/blargbot#24]

**Comment by Ratismal** [comment]
Hi, I'm sorry you seem to be having issues. The bot is functional right now, so please
1. Make sure the bot has permission to speak. This is the most common issue people have; neglecting to allow it to send messages.
2. Make sure the bot has permission to read messages. 
3. Make sure the bot doesn't have the current channel blacklisted. This probably isn't the issue.

If possible, please provide more context about the issue. For example, did you just add the bot to your guild? Are you the guild owner, or just a member? Has the bot been working fine, but suddenly stop? 

If you can't get it to work, please provide me the name or ID of your guild so I can look into it further. Also consider joining my guild [here](https://discord.gg/015GVxZxI8rtlJgXF) so that I can talk to you directly.

**Comment by Ratismal** [comment]
It's been almost a month with no response, so I'm going to go ahead and close this issue.
